# Generated by Django 3.2.3 on 2021-08-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desination',
            new_name='designation',
        ),
    ]
